version: '3.5'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      MYSQL_DATABASE: challenges
    expose:
      - 3306
